### ISSUE TITLE
Episode 001: Pulsar Basics

### ISSUE THREAD

**Issue by Anonymitaet** [streamnative/tgip-cn#10]
Check the following items when you plan to start an episode.

Assign people to each role by filling @Handle in the following parentheses.

- [x] Coordinator: (@Anonymitaet & @SylviaBABY)  

- [x] Instructor: (@sijie )

- [x] Designer: (@SylviaBABY )

## Before an episode
 
- [x] [Instructor] Pick a topic from the [episode idea backlog](https://github.com/streamnative/tgip-cn/issues?q=is%3Aopen+is%3Aissue+label%3Aepisode-idea).

- [x] [Instructor] Create a folder for the episode in the [episode folder](https://github.com/streamnative/tgip-cn/tree/master/episodes) and name it in numeric order.
  
    **Example**
    
    001, 002, 003

- [x] [Designer] Create an image for the episode and upload it to [image folder](https://github.com/streamnative/tgip-cn/tree/master/image).

- [x] [Designer] Create an image for promoting the episode and upload it to [image folder](https://github.com/streamnative/tgip-cn/tree/master/image).

- [x] [Coordinator] Publish an episode announcement with the following information to the following platforms.

  - Information:

    - [x] Topic: Pulsar architecture

    - [x] Instructor: Sijie Guo
  
    - [x] Date: Feb 9, 2020

    - [x] Time: 11:00 CST
  
    - [x] Duration: 40 min
    
    - [x] Live streaming link: https://live.bilibili.com/21468418 
  
  - Platform:

    - [x] Pulsar Slack `#china` channel

    - [x] Pulsar Slack `#tgip-cn` channel

    - [x] WeChat
 
- [x] [Instructor] Set up live stream on Bilibili with OBS. 
  
    - Note: if this is the first time for you to live stream, ask [Yu](mailto:yu@streamnative.io) to give you the username and password of StreamNative Bilibili account.
  
    - Tip: for **how to live stream on Bilibili with OBS**, see [here](https://docs.google.com/document/d/18D2Cm1eJa1EH84FTOrQoi94_57lcLLczBTq96ANlbSQ/edit).

- [x] [Instructor] Fill in the necessary information, see [here](https://github.com/streamnative/tgip-cn/blob/master/image/fill-in-info.png).
  
- [x] [Instructor] Get everything tested well:
    
    - Network
    
    - Live streaming device, such as camera, audio, and so on

## During an episode

- [x] [Instructor] Record the episode with OBS.
  
- [x] [Instructor] Make notes with HackMD: https://hackmd.io/eARaViEeR3qCXA1RZFnDwQ

- [x] [Instructor] Interact with the audience by using Bilibili **Live Chat** feature. 

## After an episode

- [x] [Instructor] Upload the recorded video to StreamNative Bilibili account.
  
  - Set the [image](https://github.com/streamnative/tgip-cn/tree/master/image) as the cover image for this episode.
  
  - Add this video to `TGIP-CN` playlist.
  
  - Add other additional information, such as title, description, and so on.

- [x] [Instructor] Add a `README.md` for the episode. 
  
    [Here](https://github.com/streamnative/tgip-cn/blob/master/episodes/episode_template.md) is a template.

- [x] [Instructor] Upload the notes to the episode folder and name it with like the following:
  
  **Example**

  001-notes.md, 002-notes.md

- [x] [Instructor] Add the episode to the [`playlist.md`](https://github.com/streamnative/tgip-cn/blob/master/playlist.md).

- [x] [Instructor] Feel free to self merge.

- [x] [Coordinator] Write a recap or a tech blog about the episode.

- [ ] [Technical writer] Improve Pulsar/SN doc based on the episode (if needed).

- [x] [Coordinator] Promote the episode with the following information to the following platforms.

  - Information:

    - [ ] Topic

    - [ ] Instructor
  
    - [ ] Date

    - [ ] Time
  
    - [ ] Duration
    
    - [ ] Recorded link

    - [ ] Recap/tech blog link
  
  - Platform:

    - [x] Pulsar Slack `#china` channel

    - [x] Pulsar Slack `#tgip-cn` channel

    - [x] WeChat

**Comment by sijie** [comment]
@Anonymitaet FYI. I have changed this to "Pulsar Basics"
