### ISSUE TITLE
Episode idea: 延时队列的设计和实现

### ISSUE THREAD

**Issue by Shoothzj** [streamnative/tgip-cn#133]
## Describe a topic you want to learn (required)
Pulsar中延时队列是如何设计和实现的。

## Why do you want to learn this topic? (required)
Pulsar中延时队列是如何设计和实现的。适用于那些场景，不适用于那些场景。精度和异常场景的可靠性是如何保证的

**Comment by tuhaihe** [comment]
@Shoothzj Here is the TGIP-CN registration page: https://www.slidestalk.com/m/333. Welcome to join us.

**Comment by Shoothzj** [comment]
Thanks, Expecting
