### ISSUE TITLE
Episode idea: KoP

### ISSUE THREAD

**Issue by sijie** [streamnative/tgip-cn#7]
## Describe a topic you want to learn (required)

How does Pulsar support Kafka protocol via KoP?

## Why do you want to learn this topic? (required)

Protocol Handler is the new mechanism introduced in Pulsar 2.5.0. KoP was developed for supporting Kafka protocol natively. I'd like to learn more about the details of KoP.

**Comment by Jennifer88huang** [comment]
It seems that we've arranged this in Episode 010 https://github.com/streamnative/tgip-cn/tree/master/episodes/010?
If so, shall we close this issue?
