### ISSUE TITLE
Episode idea: Interactive Querying of Streams Using Apache Pulsar

### ISSUE THREAD

**Issue by SylviaBABY** [streamnative/tgip-cn#80]
## Describe a topic you want to learn (required)

Pulsar Summit 中文讲解系列

## Reference (optional)
Video: https://www.youtube.com/watch?v=oYO0jk_yXZc
Slides: https://www.slideshare.net/streamnative/interactive-querying-of-streams-using-apache-pulsarjerry-peng

**Comment by Jennifer88huang** [comment]
@SylviaBABY Please arrange this as episode 019
